- name        : Check if {{ keyngo_kioskj_svc_name }} service exists in {{ ansible_hostname }}
  win_service :
     name         : '{{ keyngo_kioskj_svc_name }}'
  register: service_info

- name        : 'Insall service {{ keyngo_kioskj_svc_name }} in {{ ansible_hostname }} if not present '
  win_nssm    :
   executable   : '{{ windows_nssm_exe64 }}'
   name         : '{{ keyngo_kioskj_svc_name }}'
   application  : '{{ keyngo_kioskj_svc_launcher }}'
  when        : service_info['exists'] == false