---

- name: Ensure artifacts folder exist
  win_file:
    path: "{{ sar_tar_installation_folder }}"
    state: directory

- name: Distribute {{ sar_tar_artifact_name }}{{ sar_tar_version }} to {{ sar_tar_installation_folder }}
  win_get_url:
    url: "{{ sar_tar_nexus_url }}{{ sar_tar_artifact_name }}-{{ sar_tar_version }}.7z"
    dest: "{{ sar_tar_installation_folder }}"

- name: Transfer PSExec
  win_get_url:
    url: "{{ nexus_url }}/repository/tools/PsExec.exe"
    dest: "c:\\windows\\System32"
